### ISSUE TITLE
fusion_model-370-0.9035.pth

### ISSUE THREAD

**Issue by mikeyt14** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#11]
Hi, I am trying to run tests but I get an error since it cannot find fusion_model-370-0.9035.pth. Where can I get this file?

**Comment by YuhuiMa** [comment]
You should train your models of both stages first, then modify default settings of first_suffix, first_suffix1 and second_suffix in options.py to those of your saved model files respectively. Only then could you run tests.
