### ISSUE TITLE
Program running problems程序运行问题

### ISSUE THREAD

**Issue by Pantherk1** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#15]
我运行了front_main.py，报错
![1649939760(1)](https://user-images.githubusercontent.com/77522973/163392111-bd38fa84-4e2b-49ce-845a-297de198ce56.png)
Traceback (most recent call last):
  File "e:/OCTASNet/code/OCTANet/front_main.py", line 64, in <module>
    first_net = train_first_stage(viz, writer, train_dataloader, first_net, first_optim, args.init_lr, thin_criterion, thick_criterion, device, args.power, epoch, args.first_epochs)
  File "e:\OCTASNet\code\OCTANet\train.py", line 15, in train_first_stage
    thin_gt = sample[2].to(device)
IndexError: list index out of range

为什么sample[2].to(device)就超范围了？

**Comment by ow775** [comment]
你好，请问你是怎么解决这个问题的呢，我在运行front_main.py发现了同样的错误
