### ISSUE TITLE
../resnest50-528c19ca.pth

### ISSUE THREAD

**Issue by SGD822** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#2]
在resnest.py文件中， model_path='../resnest50-528c19ca.pth'  # /home/imed/OCT-A_segmentation/中的../resnest50-528c19ca.pth文件如何获取到？谢谢

**Comment by YuhuiMa** [comment]
你好,可通过以下链接下载:
https://hangzh.s3.amazonaws.com/encoding/models/resnest50-528c19ca.pth

**Comment by YuhuiMa** [comment]
不好意思，上述链接好像失效了，可通过以下链接下载:
https://drive.google.com/file/d/1ppa7AYgF4A4cj3YvKGnCmbraGq-nbFtO/view?usp=sharing
祝好！

**Comment by SGD822** [comment]
> 不好意思，上述链接好像失效了，可通过以下链接下载:
> https://drive.google.com/file/d/1ppa7AYgF4A4cj3YvKGnCmbraGq-nbFtO/view?usp=sharing
> 祝好！
谢谢！
