### ISSUE TITLE
Where to get "front_model-189-0.9019971996250081.pth" when using the fusion_main.py

### ISSUE THREAD

**Issue by MSC19950601** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#4]
as titling.

**Comment by YuhuiMa** [comment]
Here is the front_model-189-0.9019971996250081.pth: 
https://pan.baidu.com/s/1S852PenfG50JRWK33Zz5kg  passwd: 8fdw
Good luck!

**Comment by MSC19950601** [comment]
Thank you very much!

**Comment by MSC19950601** [comment]
Could you also provide the "370-0.9035.pth" mentioned in the option.py?

**Comment by MSC19950601** [comment]
Thank you very much!

**Comment by peterlv666** [comment]
@YuhuiMa  how to get a access to download your datasets?
