### ISSUE TITLE
dataset path

### ISSUE THREAD

**Issue by MinsWms** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#5]
Thank you very much for receiving your dataset. I encountered a problem when I replaced the data set path. Your default path is "/media/imed/data/mayuhui/TMI_OCTA_vseg/data/OCTA/CRIA", and I replaced it with "../../data/ROSE-2".and get infomation “IndexError: list index out of range”in  code\OCTA-Net\train.py, line 17, in train_first_stage  thin_gt = sample[2].to(device)。
 
That is, sampmle out of range.Hope you can answer, thank you very much！

**Comment by YuhuiMa** [comment]
We are sorry to forget to clarify that for ROSE-2, changes should be made as follows: 
thin_gt = sample[1].to(device)
thick_gt = sample[1].to(device)
if there are any bugs else, please contact us. Good luck!

**Comment by bai101315** [comment]
你好，你能给我分享一下数据集吗？下载数据集的链接失效了
