### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by roshideen** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#6]
Hi,
I tried asking for downloading dataset by sending email to yitian.zhao@nimte.ac.cn as stated in project website, but, still have not received answers yet. I also followed form as shown in the website. Could you tell me how I can access to the dataset?

**Comment by peterlv666** [comment]
I meet this questions too.Can you tell me where to get a access to download the dataset.

**Comment by roshideen** [comment]
I still haven't received accession yet.

**Comment by peterlv666** [comment]
THANKS FOR YOUR REPLY.



在 2021-03-31 11:52:02，"roshideen" ***@***.***> 写道：

I still haven't received accession yet.
