### ISSUE TITLE
keyError: 'auc'

### ISSUE THREAD

**Issue by mikeyt14** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#9]
when i run the coarse stage for ROSE-2, I get this error: 
![image](https://user-images.githubusercontent.com/72426011/120622137-6736cf00-c413-11eb-97c6-5b437bf1f51b.png)
a similar issue was posted here but was closed without offering a solution. any idea how i can solve this issue?

**Comment by YuhuiMa** [comment]
Sorry, there are some bugs in this code. "dice" in line 57-59 of front_main.py should be modified to "auc".
